### 1. Loading the Cleaned Dataset

In this step, I will load the cleaned movie dataset created during data preprocessing. This dataset will serve as the foundation for exploring movie characteristics and identifying patterns in the data.

In [6]:
from pathlib import Path

import pandas as pd
import numpy as np
from IPython.display import display

PROJECT_ROOT = Path.cwd()

if PROJECT_ROOT.name == "notebooks":
    PROJECT_ROOT = PROJECT_ROOT.parent

data_path = PROJECT_ROOT / "data" / "processed" / "tmdb_movies_cleaned.csv"

df = pd.read_csv(data_path, parse_dates=["release_date"])

print("Dataset loaded successfully!")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

display(df.head())

Dataset loaded successfully!
Rows: 18
Columns: 22

,id,title,tagline,release_date,genres,belongs_to_collection,original_language,budget_musd,revenue_musd,production_companies,...,vote_average,popularity,runtime,overview,spoken_languages,poster_path,cast,cast_size,director,crew_size
0,299534,Avengers: Endgame,Avenge the fallen.,2019-04-24,Adventure | Science Fiction | Action,The Avengers Collection,en,356.0,2927.449455,Marvel Studios,...,8.200,87.1502,181,After the devastating events of Avengers: Infi...,English | Japanese | Xhosa,/bR8ISy1O9XQxqiy0fQFw2BX72RQ.jpg,"['Robert Downey Jr.', 'Chris Evans', 'Mark Ruf...",103,Anthony Russo | Joe Russo,613
1,19995,Avatar,Enter the world of Pandora.,2009-12-16,Science Fiction | Action | Adventure,Avatar Collection,en,237.0,2923.706026,Dune Entertainment | Lightstorm Entertainment ...,...,7.611,48.3380,162,"In the 22nd century, a paraplegic Marine is di...",English | Spanish,/gKY6q7SjCkAU6FqvqWybDYgUKIF.jpg,"['Sam Worthington', 'Zoe Saldaña', 'Sigourney ...",68,James Cameron,999
2,140607,Star Wars: The Force Awakens,Every generation has a story.,2015-12-15,Adventure | Action | Science Fiction,Star Wars Collection,en,245.0,2068.223624,Lucasfilm Ltd. | Bad Robot,...,7.200,45.2373,136,Thirty years after defeating the Galactic Empi...,English,/wqnLdwVXoBjKibFRR5U3y0aDUhs.jpg,"['Daisy Ridley', 'John Boyega', 'Oscar Isaac',...",99,J.J. Abrams,270
3,299536,Avengers: Infinity War,An entire universe. Once and for all.,2018-04-25,Adventure | Action | Science Fiction,The Avengers Collection,en,300.0,2052.415039,Marvel Studios,...,8.245,142.7426,149,As the Avengers and their allies have continue...,English | Xhosa,/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg,"['Robert Downey Jr.', 'Chris Evans', 'Chris He...",69,Joe Russo | Anthony Russo,738
4,597,Titanic,Nothing on earth could come between them.,1997-12-18,Drama | Romance,NaN,en,200.0,2264.162353,Paramount Pictures | 20th Century Fox | Lights...,...,7.901,65.2492,194,101-year-old Rose DeWitt Bukater tells the sto...,English | French | German | Swedish | Italian ...,/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg,"['Leonardo DiCaprio', 'Kate Winslet', 'Billy Z...",116,James Cameron,271

In [7]:
df.iloc[3]

id                                                                  299536
title                                               Avengers: Infinity War
tagline                              An entire universe. Once and for all.
release_date                                           2018-04-25 00:00:00
genres                                Adventure | Action | Science Fiction
belongs_to_collection                              The Avengers Collection
original_language                                                       en
budget_musd                                                          300.0
revenue_musd                                                   2052.415039
production_companies                                        Marvel Studios
production_countries                              United States of America
vote_count                                                           33148
vote_average                                                         8.245
popularity                                                        142.7426
runtime                                                                149
overview                 As the Avengers and their allies have continue...
spoken_languages                                           English | Xhosa
poster_path                               /7WsyChQLEftFiDOVTGkv3hFpyyt.jpg
cast                     ['Robert Downey Jr.', 'Chris Evans', 'Chris He...
cast_size                                                               69
director                                         Joe Russo | Anthony Russo
crew_size                                                              738
Name: 3, dtype: object

### 2. Understanding the Dataset Structure

I will inspect the dataset's dimensions, column names, data types, and non-missing values. This helps me understand the information available and confirm that the data is ready for analysis.

In [8]:
print("Dataset dimensions:", df.shape)

print("\nColumn names:")
print(df.columns.tolist())

print("\nDataset information:")
df.info()

Dataset dimensions: (18, 22)

Column names:
['id', 'title', 'tagline', 'release_date', 'genres', 'belongs_to_collection', 'original_language', 'budget_musd', 'revenue_musd', 'production_companies', 'production_countries', 'vote_count', 'vote_average', 'popularity', 'runtime', 'overview', 'spoken_languages', 'poster_path', 'cast', 'cast_size', 'director', 'crew_size']

Dataset information:
<class 'pandas.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 22 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     18 non-null     int64
 1   title                  18 non-null     str
 2   tagline                18 non-null     str
 3   release_date           18 non-null     datetime64[us]
 4   genres                 18 non-null     str
 5   belongs_to_collection  16 non-null     str
 6   original_language      18 non-null     str
 7   budget_musd            18 non-null     float64
 8   revenue_musd           18 non-null     float64
 9   production_companies   18 non-null     str
 10  production_countries   18 non-null     str
 11  vote_count             18 non-null     int64
 12  vote_average           18 non-null     float64
 13  popularity             18 non-null     float64
 14  runtime                18 non-null     int64
 15  overview               18 non-null     str
 16  spoken_languages       18 non-null     str
 17  poster_path            18 non-null     str
 18  cast                   18 non-null     str
 19  cast_size              18 non-null     int64
 20  director               18 non-null     str
 21  crew_size              18 non-null     int64
dtypes: datetime64[us](1), float64(4), int64(5), str(12)
memory usage: 3.2 KB

### 3. Descriptive Statistics

Descriptive statistics summarize the numerical characteristics of the movies. I will examine budgets, revenues, ratings, popularity, runtime, and vote counts to understand their typical values and variation.

In [9]:
numeric_columns = [
    "budget_musd",
    "revenue_musd",
    "vote_count",
    "vote_average",
    "popularity",
    "runtime",
    "cast_size",
    "crew_size",
]

display(df[numeric_columns].describe().round(2))

,budget_musd,revenue_musd,vote_count,vote_average,popularity,runtime,cast_size,crew_size
count,18.00,18.00,18.00,18.00,18.00,18.00,18.00,18.00
mean,213.78,1699.04,21713.94,7.40,54.51,138.00,79.94,390.67
std,61.96,537.61,8732.03,0.53,27.51,23.85,30.99,260.02
min,125.00,1243.23,10512.00,6.50,31.29,102.00,20.00,43.00
25%,162.50,1336.18,14565.50,7.12,36.42,125.25,61.00,212.00
50%,200.00,1484.54,21510.50,7.26,46.12,135.50,72.00,279.50
75%,243.00,1957.20,27218.50,7.83,62.57,147.50,106.00,606.25
max,356.00,2927.45,40032.00,8.24,142.74,194.00,139.00,999.00

### 4. Creating Financial KPIs

Profit is calculated as revenue minus budget. Return on Investment (ROI) measures revenue relative to the production budget. Both metrics will be calculated in millions of US dollars where applicable. ROI will be calculated only for movies with a known, positive budget.

In [10]:
df["profit_musd"] = df["revenue_musd"] - df["budget_musd"]

df["roi"] = np.where(
    df["budget_musd"] > 0,
    df["revenue_musd"] / df["budget_musd"],
    np.nan
)

display(
    df[
        ["title", "budget_musd", "revenue_musd", "profit_musd", "roi"]
    ].head(10)
)

,title,budget_musd,revenue_musd,profit_musd,roi
0,Avengers: Endgame,356.0,2927.449455,2571.449455,8.223173
1,Avatar,237.0,2923.706026,2686.706026,12.336312
2,Star Wars: The Force Awakens,245.0,2068.223624,1823.223624,8.441729
3,Avengers: Infinity War,300.0,2052.415039,1752.415039,6.841383
4,Titanic,200.0,2264.162353,2064.162353,11.320812
5,Jurassic World,150.0,1671.537444,1521.537444,11.143583
6,The Lion King,260.0,1662.020819,1402.020819,6.392388
7,The Avengers,220.0,1518.815515,1298.815515,6.903707
8,Furious 7,190.0,1515.400000,1325.400000,7.975789
9,Avengers: Age of Ultron,235.0,1405.403694,1170.403694,5.980441

### 5. Defining a User-Defined Ranking Function

I will create a reusable function to rank movies by a selected KPI. This avoids repeating similar code for each ranking and allows the same function to identify both the highest and lowest values.

In [11]:
def rank_movies(data, metric, ascending=False, top_n=5, min_votes=None):
    """
    Rank movies by a numeric metric.

    Parameters:
        data: DataFrame containing movie information
        metric: Column used for ranking
        ascending: False for highest first, True for lowest first
        top_n: Number of movies to return
        min_votes: Optional minimum vote count

    Returns:
        DataFrame of ranked movies
    """
    result = data.copy()

    result[metric] = pd.to_numeric(result[metric], errors="coerce")
    result = result.dropna(subset=[metric])

    if min_votes is not None:
        result = result[result["vote_count"] >= min_votes]

    return result.sort_values(
        metric, ascending=ascending
    ).head(top_n)

### 6. Ranking Movies by KPIs

I will use the ranking function to identify movies with the highest revenue, highest budget, highest and lowest profit, highest and lowest ROI, most votes, highest and lowest ratings, and greatest popularity. Rankings will exclude missing KPI values and apply the specified eligibility rules.

In [12]:
print("\nHighest revenue movies:")
display(rank_movies(df, "revenue_musd")[
    ["title", "revenue_musd", "budget_musd"]
])

Highest revenue movies:

                          title  revenue_musd  budget_musd
0             Avengers: Endgame   2927.449455        356.0
1                        Avatar   2923.706026        237.0
4                       Titanic   2264.162353        200.0
2  Star Wars: The Force Awakens   2068.223624        245.0
3        Avengers: Infinity War   2052.415039        300.0

In [13]:
print("\nHighest budget movies:")
display(rank_movies(df, "budget_musd")[
    ["title", "budget_musd", "revenue_musd"]
])

Highest budget movies:

                           title  budget_musd  revenue_musd
0              Avengers: Endgame        356.0   2927.449455
3         Avengers: Infinity War        300.0   2052.415039
12      Star Wars: The Last Jedi        300.0   1334.407706
6                  The Lion King        260.0   1662.020819
2   Star Wars: The Force Awakens        245.0   2068.223624

In [14]:
print("\nHighest profit movies:")
display(rank_movies(df, "profit_musd")[
    ["title", "profit_musd", "revenue_musd", "budget_musd"]
])

print("\nLowest profit movies:")
display(rank_movies(df, "profit_musd", ascending=True)[
    ["title", "profit_musd", "revenue_musd", "budget_musd"]
])

Highest profit movies:

                          title  profit_musd  revenue_musd  budget_musd
1                        Avatar  2686.706026   2923.706026        237.0
0             Avengers: Endgame  2571.449455   2927.449455        356.0
4                       Titanic  2064.162353   2264.162353        200.0
2  Star Wars: The Force Awakens  1823.223624   2068.223624        245.0
3        Avengers: Infinity War  1752.415039   2052.415039        300.0

Lowest profit movies:

                             title  profit_musd  revenue_musd  budget_musd
12        Star Wars: The Last Jedi  1034.407706   1334.407706        300.0
17                   Incredibles 2  1043.225667   1243.225667        200.0
16            Beauty and the Beast  1106.115964   1266.115964        160.0
15                          Frozen  1124.219009   1274.219009        150.0
14  Jurassic World: Fallen Kingdom  1140.469037   1310.469037        170.0

In [15]:
print("\nHighest ROI movies:")
eligible_roi = df[df["budget_musd"] >= 10].copy()

display(rank_movies(eligible_roi, "roi")[
    ["title", "budget_musd", "revenue_musd", "roi"]
])
print("\nLowest ROI movies:")
display(rank_movies(eligible_roi, "roi", ascending=True)[
    ["title", "budget_musd", "revenue_musd", "roi"]
])

Highest ROI movies:

,title,budget_musd,revenue_musd,roi
1,Avatar,237.0,2923.706026,12.336312
4,Titanic,200.0,2264.162353,11.320812
5,Jurassic World,150.0,1671.537444,11.143583
11,Harry Potter and the Deathly Hallows: Part 2,125.0,1341.511219,10.732090
13,Frozen II,150.0,1453.683476,9.691223

Lowest ROI movies:

                       title  budget_musd  revenue_musd       roi
12  Star Wars: The Last Jedi        300.0   1334.407706  4.448026
9    Avengers: Age of Ultron        235.0   1405.403694  5.980441
17             Incredibles 2        200.0   1243.225667  6.216128
6              The Lion King        260.0   1662.020819  6.392388
10             Black Panther        200.0   1349.926083  6.749630

In [16]:
print("\nHighest vote count movies:")
display(rank_movies(df, "vote_count")[
    ["title", "vote_count", "vote_average"]
])

Highest vote count movies:

                    title  vote_count  vote_average
7            The Avengers       40032         8.100
1                  Avatar       34845         7.611
3  Avengers: Infinity War       33148         8.245
0       Avengers: Endgame       29005         8.200
4                 Titanic       27901         7.901

In [17]:
print("\nHighest rated movies (with at least 10 votes):")
display(rank_movies(df, "vote_average", min_votes=10)[
    ["title", "vote_average", "vote_count"]
])

print("\nLowest rated movies (with at least 10 votes):")
display(rank_movies(
    df, "vote_average", ascending=True, min_votes=10
)[["title", "vote_average", "vote_count"]])

Highest rated movies (with at least 10 votes):

                                           title  vote_average  vote_count
3                         Avengers: Infinity War         8.245       33148
0                              Avengers: Endgame         8.200       29005
7                                   The Avengers         8.100       40032
11  Harry Potter and the Deathly Hallows: Part 2         8.081       22569
4                                        Titanic         7.901       27901

Lowest rated movies (with at least 10 votes):

                             title  vote_average  vote_count
14  Jurassic World: Fallen Kingdom         6.500       13073
5                   Jurassic World         6.702       22008
12        Star Wars: The Last Jedi         6.733       16774
16            Beauty and the Beast         6.969       16217
6                    The Lion King         7.090       10953

In [18]:
print("\nHighest popularity movies:")
display(rank_movies(df, "popularity")[
    ["title", "popularity", "vote_average"]
])

Highest popularity movies:

                     title  popularity  vote_average
3   Avengers: Infinity War    142.7426         8.245
0        Avengers: Endgame     87.1502         8.200
7             The Avengers     83.0978         8.100
9  Avengers: Age of Ultron     65.4620         7.278
4                  Titanic     65.2492         7.901

### 7. Advanced Movie Filtering and Search Queries

I will filter the dataset using actor, director, and genre information. The first query identifies highly rated Science Fiction and Action movies featuring Bruce Willis. The second identifies movies featuring Uma Thurman and directed by Quentin Tarantino, ordered by runtime from shortest to longest.

In [19]:
search_1 = df[
    df["cast"].str.contains("Bruce Willis", case=False, na=False)
    & df["genres"].str.contains("Science Fiction", case=False, na=False)
    & df["genres"].str.contains("Action", case=False, na=False)
]

search_1 = search_1.sort_values("vote_average", ascending=False)

display(search_1[
    ["title", "genres", "vote_average", "vote_count", "cast"]
])

Empty DataFrame
Columns: [title, genres, vote_average, vote_count, cast]
Index: []

In [20]:
search_2 = df[
    df["cast"].str.contains("Uma Thurman", case=False, na=False)
    & df["director"].str.contains(
        "Quentin Tarantino", case=False, na=False
    )
]

search_2 = search_2.sort_values("runtime", ascending=True)

display(search_2[
    ["title", "director", "runtime", "vote_average", "cast"]
])

Empty DataFrame
Columns: [title, director, runtime, vote_average, cast]
Index: []

### 8. Most Successful Movie Franchises

I will group movies by their collection name and calculate the number of movies, total and mean production budget, total and mean revenue, and mean rating for each franchise. These metrics will help compare the financial performance and audience ratings of different franchises.

In [21]:
franchise_df = df[df["belongs_to_collection"].notna()].copy()

franchise_summary = (
    franchise_df.groupby("belongs_to_collection")
    .agg(
        total_movies=("id", "count"),
        total_budget_musd=("budget_musd", "sum"),
        mean_budget_musd=("budget_musd", "mean"),
        total_revenue_musd=("revenue_musd", "sum"),
        mean_revenue_musd=("revenue_musd", "mean"),
        mean_rating=("vote_average", "mean"),
    )
    .sort_values("total_revenue_musd", ascending=False)
)

display(franchise_summary.round(2))

,total_movies,total_budget_musd,mean_budget_musd,total_revenue_musd,mean_revenue_musd,mean_rating
belongs_to_collection,,,,,,
The Avengers Collection,4,1111.0,277.75,7904.08,1976.02,7.96
Star Wars Collection,2,545.0,272.50,3402.63,1701.32,6.97
Jurassic Park Collection,2,320.0,160.00,2982.01,1491.00,6.60
Avatar Collection,1,237.0,237.00,2923.71,2923.71,7.61
Frozen Collection,2,300.0,150.00,2727.90,1363.95,7.24
The Lion King (Reboot) Collection,1,260.0,260.00,1662.02,1662.02,7.09
The Fast and the Furious Collection,1,190.0,190.00,1515.40,1515.40,7.21
Black Panther Collection,1,200.0,200.00,1349.93,1349.93,7.40
Harry Potter Collection,1,125.0,125.00,1341.51,1341.51,8.08
The Incredibles Collection,1,200.0,200.00,1243.23,1243.23,7.45

In [22]:
print("\nTop 10 franchises by total movies:")
display(
    franchise_summary
    .sort_values("total_movies", ascending=False)
    .head(10)
    .round(2)
)

Top 10 franchises by total movies:

,total_movies,total_budget_musd,mean_budget_musd,total_revenue_musd,mean_revenue_musd,mean_rating
belongs_to_collection,,,,,,
The Avengers Collection,4,1111.0,277.75,7904.08,1976.02,7.96
Star Wars Collection,2,545.0,272.50,3402.63,1701.32,6.97
Jurassic Park Collection,2,320.0,160.00,2982.01,1491.00,6.60
Frozen Collection,2,300.0,150.00,2727.90,1363.95,7.24
Avatar Collection,1,237.0,237.00,2923.71,2923.71,7.61
The Lion King (Reboot) Collection,1,260.0,260.00,1662.02,1662.02,7.09
The Fast and the Furious Collection,1,190.0,190.00,1515.40,1515.40,7.21
Black Panther Collection,1,200.0,200.00,1349.93,1349.93,7.40
Harry Potter Collection,1,125.0,125.00,1341.51,1341.51,8.08
The Incredibles Collection,1,200.0,200.00,1243.23,1243.23,7.45

In [23]:
print("\nTop 10 franchises by total revenue:")
display(franchise_summary.head(10).round(2))

Top 10 franchises by total revenue:

,total_movies,total_budget_musd,mean_budget_musd,total_revenue_musd,mean_revenue_musd,mean_rating
belongs_to_collection,,,,,,
The Avengers Collection,4,1111.0,277.75,7904.08,1976.02,7.96
Star Wars Collection,2,545.0,272.50,3402.63,1701.32,6.97
Jurassic Park Collection,2,320.0,160.00,2982.01,1491.00,6.60
Avatar Collection,1,237.0,237.00,2923.71,2923.71,7.61
Frozen Collection,2,300.0,150.00,2727.90,1363.95,7.24
The Lion King (Reboot) Collection,1,260.0,260.00,1662.02,1662.02,7.09
The Fast and the Furious Collection,1,190.0,190.00,1515.40,1515.40,7.21
Black Panther Collection,1,200.0,200.00,1349.93,1349.93,7.40
Harry Potter Collection,1,125.0,125.00,1341.51,1341.51,8.08
The Incredibles Collection,1,200.0,200.00,1243.23,1243.23,7.45

### 9. Most Successful Directors

I will group movies by director and calculate the number of movies directed, total revenue, and mean rating. This will help identify directors with the highest combined box-office revenue and compare their average audience ratings.

In [24]:
director_df = df.dropna(subset=["director"]).copy()

director_df["director"] = (
    director_df["director"].str.split(" | ", regex=False)
)

director_df = director_df.explode("director")

director_df["director"] = director_df["director"].str.strip()

director_df = director_df[
    director_df["director"].ne("")
]

Now calculate the director metrics:

In [25]:
director_summary = (
    director_df.groupby("director")
    .agg(
        total_movies=("id", "nunique"),
        total_revenue_musd=("revenue_musd", "sum"),
        mean_rating=("vote_average", "mean"),
    )
    .sort_values("total_revenue_musd", ascending=False)
)

display(director_summary.round(2))

                 total_movies  total_revenue_musd  mean_rating
director
James Cameron               2             5187.87         7.76
Anthony Russo               2             4979.86         8.22
Joe Russo                   2             4979.86         8.22
Joss Whedon                 2             2924.22         7.69
Jennifer Lee                2             2727.90         7.24
Chris Buck                  2             2727.90         7.24
J.J. Abrams                 1             2068.22         7.20
Colin Trevorrow             1             1671.54         6.70
Jon Favreau                 1             1662.02         7.09
James Wan                   1             1515.40         7.21
Ryan Coogler                1             1349.93         7.40
David Yates                 1             1341.51         8.08
Rian Johnson                1             1334.41         6.73
J. A. Bayona                1             1310.47         6.50
Bill Condon                 1             1266.12         6.97
Brad Bird                   1             1243.23         7.45

Show the directors with the most movies in the dataset:

In [26]:
display(
    director_summary
    .sort_values("total_movies", ascending=False)
    .head(10)
    .round(2)
)

                 total_movies  total_revenue_musd  mean_rating
director
James Cameron               2             5187.87         7.76
Anthony Russo               2             4979.86         8.22
Joe Russo                   2             4979.86         8.22
Joss Whedon                 2             2924.22         7.69
Jennifer Lee                2             2727.90         7.24
Chris Buck                  2             2727.90         7.24
J.J. Abrams                 1             2068.22         7.20
Colin Trevorrow             1             1671.54         6.70
Jon Favreau                 1             1662.02         7.09
James Wan                   1             1515.40         7.21